server:
  port: 8091
spring:
  main:
    banner-mode: off
  jpa:
      show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test

todoist:
  uri: https://api.todoist.com/sync/v8/sync

db:
  namespace: ptpb
  port: 3000
  host: localhost
